In [84]:
#Array and shape 1D Array
import numpy as np
cpu_usage = np.array([42,55,78,91,63])
print(cpu_usage)
print("shape", cpu_usage.shape)
print("dtype", cpu_usage.dtype)

[42 55 78 91 63]
shape (5,)
dtype int64


In [85]:
import numpy as np
cpu_usage1 = np.array([56,87,99,12,35])
print("cpu usage", cpu_usage1)
print("shape",cpu_usage1.shape)
print("dtype",cpu_usage1.dtype)

cpu usage [56 87 99 12 35]
shape (5,)
dtype int64


In [86]:
#2D ARRAYS - 3 servers x 5 time steps
metrics = np.array([
    [42,55,78,91,63], 
    [30,35,40,38,45],
    [88,92,95,97,99] ])
print("shape", metrics.shape)
print("ndim", metrics.ndim)

shape (3, 5)
ndim 2


In [87]:
import numpy as np

# 1. 1D array of memory usage (in %) for 6 time steps:
memory = np.array([60,65,70,68,85,90])

# 2. Print shape, ndim, and dtype. these are attributes..doesnt have ()
print(memory.shape)
print(memory.ndim)
print(memory.dtype)

# 3. 2D array with 2 servers and 4 readings each:

servers = np.array([
    [50,60,55,70], 
    [80,85,90,88],
])

# 4. shape of servers 
print(servers.shape)

# 5. Array of 6 evenly spaced alert thresholds between 50 and 100
thresholds = np.linspace(50,100,6)
print(thresholds)
print(thresholds.dtype)

(6,)
1
int64
(2, 4)
[ 50.  60.  70.  80.  90. 100.]
float64


In [88]:
scores = [24,25,27,90,67,88]
print(scores)  # prints a list with commas

[24, 25, 27, 90, 67, 88]


In [89]:
import numpy as np
scores = np.array(scores)
print(scores)   # prints an array, no commas..declaread as an array in line above
# Print min, max, mean, sum , std . these are methods..have ()
print(scores.min())
print(scores.max())
print(scores.mean())
print(scores.sum())
print(scores*2)

[24 25 27 90 67 88]
24
90
53.5
321
[ 48  50  54 180 134 176]


In [90]:
import numpy as np
score = np.array([45,58,78,90])
print(score)
print("shape", score.shape)
print("min value", score.min())
print(score.max())
print(score*2)
# Average
print("Mean:", score.mean())

# Boolean mask — which scores are above 70
print("Above 70:", score > 70)
print("Above 70", score[score>70])
print("belwo 70", score[score<70])

[45 58 78 90]
shape (4,)
min value 45
90
[ 90 116 156 180]
Mean: 67.75
Above 70: [False False  True  True]
Above 70 [78 90]
belwo 70 [45 58]


In [91]:
print(score.shape)
print(score.max())
print(score.min())
print(score.sum())
print(score*2)

(4,)
90
45
271
[ 90 116 156 180]


In [92]:
import numpy as np

# Each row is a student, each column is a subject
marks = np.array([
    [45, 78, 90],   # shiva
    [58, 82, 76],   # john
    [92, 88, 95],   # marry
    [98, 74, 88]    # ram
])

# 1 - print shape
print("Shape:", marks.shape)  

# 2 - average score of each student (row wise)
print("Student averages:", marks.mean(axis=1))  

# 3 - average score of each subject (column wise)
print("Subject averages:", marks.mean(axis=0))   

Shape: (4, 3)
Student averages: [71.         72.         91.66666667 86.66666667]
Subject averages: [73.25 80.5  87.25]


In [93]:
import numpy as np
marks = np.array([
    [45,65,98],
    [67,37,88],
    [87,48,79]
    ])

print(marks)
print("shape", marks.shape)
print("student average", marks.mean(axis = 1))
print("average marks of each subject", marks.mean(axis = 0))

[[45 65 98]
 [67 37 88]
 [87 48 79]]
shape (3, 3)
student average [69.33333333 64.         71.33333333]
average marks of each subject [66.33333333 50.         88.33333333]


In [94]:
# Dataset — 5 students, 3 subjects (Math, Science, English)
import numpy as np
marks = np.array([
    [45, 78, 90],
    [58, 82, 76],
    [92, 88, 95],
    [98, 74, 88],
    [40, 55, 60]
])

print("shape", marks.shape)
print("average of each student", marks.mean(axis = 1))
print("average of each subject", marks.mean(axis = 0))
print("highest scored in the entire database", marks.max())
print("gives true or false for the conditions student average > 80", marks.mean(axis=1)>80) #boolean mask
print("students scored above 80 average", marks[marks.mean(axis=1)>80])  #boolean masking for dataframe, only prints where condition is true.
print("multiply", marks*1.1)

shape (5, 3)
average of each student [71.         72.         91.66666667 86.66666667 51.66666667]
average of each subject [66.6 75.4 81.8]
highest scored in the entire database 98
gives true or false for the conditions student average > 80 [False False  True  True False]
students scored above 80 average [[92 88 95]
 [98 74 88]]
multiply [[ 49.5  85.8  99. ]
 [ 63.8  90.2  83.6]
 [101.2  96.8 104.5]
 [107.8  81.4  96.8]
 [ 44.   60.5  66. ]]


In [95]:
#Dataset - 5 servers, 6 time steps for cpu_metrics
import numpy as np
import numpy as np
cpu_metrics = np.array([
    [84, 87, 90, 83, 94, 150],   
    [78, 57, 78, 56, 89, 91],
    [56, 74, 46, 58, 69, 79],
    [87, 76, 65, 54, 94, 160],   
    [60, 62, 61, 59, 63, 64]
])
print(cpu_metrics)
print("shape", np.shape(cpu_metrics))
print("shape", cpu_metrics.shape)   #cannot use .shape()...gives error...it works in 1D only becoz shape is an attribute...only methods have ()
print("average of all server cpu readings-global", cpu_metrics.mean)
print("standard deviation of all servers-global", cpu_metrics.std)
print("average of each server", cpu_metrics.mean(axis=1))  #server wise
print("average of all servers at particular time ", cpu_metrics.mean(axis=0))  #time wise for all servers
print("high cpu among all servers", cpu_metrics.max())
print("servers with above 80 average", cpu_metrics[cpu_metrics.mean(axis=1) >80]) 
print("multiply server metrics with 1.1", cpu_metrics * 1.1)

[[ 84  87  90  83  94 150]
 [ 78  57  78  56  89  91]
 [ 56  74  46  58  69  79]
 [ 87  76  65  54  94 160]
 [ 60  62  61  59  63  64]]
shape (5, 6)
shape (5, 6)
average of all server cpu readings-global <built-in method mean of numpy.ndarray object at 0x00000206C2E6A730>
standard deviation of all servers-global <built-in method std of numpy.ndarray object at 0x00000206C2E6A730>
average of each server [98.         74.83333333 63.66666667 89.33333333 61.5       ]
average of all servers at particular time  [ 73.   71.2  68.   62.   81.8 108.8]
high cpu among all servers 160
servers with above 80 average [[ 84  87  90  83  94 150]
 [ 87  76  65  54  94 160]]
multiply server metrics with 1.1 [[ 92.4  95.7  99.   91.3 103.4 165. ]
 [ 85.8  62.7  85.8  61.6  97.9 100.1]
 [ 61.6  81.4  50.6  63.8  75.9  86.9]
 [ 95.7  83.6  71.5  59.4 103.4 176. ]
 [ 66.   68.2  67.1  64.9  69.3  70.4]]


In [1]:
#combining into single dataset
import numpy as np

# CPU usage for 3 servers
cpu = np.array([60, 75, 90])

# Memory usage for same servers
memory = np.array([70, 65, 95])

# Combine into single dataset
metrics = np.array([cpu, memory])

print(metrics)

[[60 75 90]
 [70 65 95]]


In [3]:
# 3D data → servers × time × metrics
data = np.random.randint(30, 100, size=(5, 10, 2))  #5 servers, 10 time stamps, 2 metrics( cpu, ram)
print(data)
print(data.shape)

[[[58 79]
  [33 84]
  [30 87]
  [67 84]
  [94 32]
  [93 31]
  [64 88]
  [86 92]
  [69 45]
  [71 64]]

 [[68 66]
  [74 40]
  [40 84]
  [61 31]
  [32 45]
  [87 50]
  [64 54]
  [47 74]
  [73 95]
  [71 43]]

 [[33 32]
  [41 48]
  [96 90]
  [51 65]
  [49 75]
  [50 33]
  [31 68]
  [84 55]
  [70 52]
  [38 69]]

 [[39 70]
  [88 55]
  [86 88]
  [85 91]
  [43 72]
  [75 81]
  [79 73]
  [93 83]
  [61 60]
  [72 84]]

 [[36 48]
  [45 50]
  [69 84]
  [77 33]
  [33 65]
  [44 37]
  [88 76]
  [97 73]
  [41 75]
  [39 86]]]
(5, 10, 2)
