In [2]:
#Boolean Logic and Filtering
#single condition
import numpy as np
cpu = np.array([42,55,78,91,63,88,30])
print(cpu >75) # F F F TT T
print(cpu[cpu>75]) # [FILTERS THE TRUE VALUES]

[False False  True  True False  True False]
[78 91 88]


In [4]:
#multiple contions AND,OR,NOT  
cpu = np.array([42,55,78,91,63,88,30])
print(cpu[(cpu>60) & (cpu<90)])  #AND
print(cpu[(cpu <40) | (cpu>85)  ])  #OR
print(cpu[~(cpu>75)])  #not - inverst the condition

[78 63 88]
[91 88 30]
[42 55 63 30]


In [11]:
# np.where - positions and values together
cpu = np.array([42,55,78,91,63,88,30])
print(cpu)
indx = np.where(cpu > 75)
print(indx)
print(cpu[indx])
flags = np.where(cpu>75,1,0)   #np.where with arguements - if/else on entire array, replace value with 1 else 0
print(flags)

[42 55 78 91 63 88 30]
(array([2, 3, 5]),)
[78 91 88]
[0 0 1 1 0 1 0]


In [3]:
#Applying logic across 2D arrays
# np.any — at least one reading meets the condition.
# np.all — every reading meets the condition.
servers = np.array([
    [42,55,78,91,63],
    [30,35,40,38,45],
    [88,92,95,97,99],
])
print(servers)
print(servers[servers>80])
print(np.any(servers > 90, axis = 1))  # across rows T OR F
print(np.all(servers > 40, axis =1))

[[42 55 78 91 63]
 [30 35 40 38 45]
 [88 92 95 97 99]]
[91 88 92 95 97 99]
[ True False  True]
[ True False  True]


In [4]:
# counting alerts
cpu = np.array([42,55,78,91,63,88,30])
print(np.sum(cpu))  # sum of all cpu readings
print(np.sum(cpu>75)) # sum of how many reading exceed 75 np.sum boolean array counts the trues.
print(np.mean(cpu>75) *100) # boolean array gives the proportion multiply by 100 gives percentage.

447
3
42.857142857142854


In [2]:
#all together
import numpy as np
servers = np.array([
    [55,60,78,91,85],
    [30,32,35,33,31],
    [70,75,88,95,99],

])
latency = np.array([12,15,14,45,16,13,60,18])
# 1. Print all readings across all servers above 80
print(servers[servers>80])

# 2. Print latency values that are above 20 AND below 50
print(latency[(latency >20) & (latency <50)])

# 3. Which servers have at least one reading above 90?
print(np.any(servers >90, axis=1))

# 4. Flag every latency reading — 1 if above 20ms, 0 if normal
flags = np.where(latency >20,1,0)
print(flags)

# # 5. How many latency readings exceeded 20ms?
print(np.sum(latency > 20))

# # 6. What percentage of latency readings were above 20ms?
print(f"{np.mean(latency>20)*100:.1f}%")

[91 85 88 95 99]
[45]
[ True False  True]
[0 0 0 1 0 0 1 0]
2
25.0%


In [5]:
#Dataset - 5 servers, 6 time steps for cpu_metrics
import numpy as np
cpu_metrics = np.array([
    [84, 87, 90, 83, 94, 150],   
    [78, 57, 78, 56, 89, 91],
    [56, 74, 46, 58, 69, 79],
    [87, 76, 65, 54, 94, 160],  
    [60, 62, 61, 59, 63, 64]
])
print(cpu_metrics)
print("shape", np.shape(cpu_metrics))
print("average of all server cpu readings-global", cpu_metrics.mean)
print("standard deviation of all servers-global", cpu_metrics.std)
print("average of each server", cpu_metrics.mean(axis=1))  #server wise
print("average of all servers at particular time ", cpu_metrics.mean(axis=0))  #time wise for all servers
print("high cpu among all servers", cpu_metrics.max())
print("servers with above 80 average", cpu_metrics[cpu_metrics.mean(axis=1) >80]) 
row_mean = cpu_metrics.mean(axis=1)
row_std = cpu_metrics.std(axis=1)

threshold = row_mean + 2 * row_std
anomalies = []

for i in range(len(cpu_metrics)):
    anomalies.append(cpu_metrics[i] > threshold[i])

anomalies = np.array(anomalies)
print(anomalies)

anomalies = np.array(anomalies)
servers_with_anomaly = anomalies.any(axis=1)
print("servers with anomalies:\n", cpu_metrics[servers_with_anomaly])

[[ 84  87  90  83  94 150]
 [ 78  57  78  56  89  91]
 [ 56  74  46  58  69  79]
 [ 87  76  65  54  94 160]
 [ 60  62  61  59  63  64]]
shape (5, 6)
average of all server cpu readings-global <built-in method mean of numpy.ndarray object at 0x000001FC282A9DD0>
standard deviation of all servers-global <built-in method std of numpy.ndarray object at 0x000001FC282A9DD0>
average of each server [98.         74.83333333 63.66666667 89.33333333 61.5       ]
average of all servers at particular time  [ 73.   71.2  68.   62.   81.8 108.8]
high cpu among all servers 160
servers with above 80 average [[ 84  87  90  83  94 150]
 [ 87  76  65  54  94 160]]
[[False False False False False  True]
 [False False False False False False]
 [False False False False False False]
 [False False False False False  True]
 [False False False False False False]]
servers with anomalies:
 [[ 84  87  90  83  94 150]
 [ 87  76  65  54  94 160]]
