In [3]:
#Reshaping and Dimensions
#arange
import numpy as np
cpu = np.arange(12)
print(cpu)
print(cpu.shape)

#reshape to 3 servers x 4 time steps
grid = cpu.reshape(3,4)
print(grid)
print(grid.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)


In [11]:
print(cpu.reshape(-1,4)) #need 4 columns, numpy figure out no of rows

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [12]:
print(cpu.reshape(3,-1)) #need 3 rows, numpy figure out no of columns

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [14]:
flat = np.array([42,55,78,91]) #reshape to single column or column vector
print(flat.reshape(-1,1))

[[42]
 [55]
 [78]
 [91]]


In [19]:
#flatten and ravel - back to 1D
grid = np.array([[42,55,78],
                [30,35,40],
])
print(grid.flatten())
print(grid.ravel())

[42 55 78 30 35 40]
[42 55 78 30 35 40]


In [4]:
#newaxis - adding a dimension
import numpy as np
cpu = np.array([42,55,78,91])
print(cpu.shape)
print(cpu[np.newaxis, :].shape) #makes it row vector
print(cpu[: , np.newaxis].shape) #makes it column vector #np.newaxis is identical to reshape(-1,1)

(4,)
(1, 4)
(4, 1)


In [10]:
#stack - combining arrays into higher dimensions
server_a = np.array([42,55,78,91])
server_b = np.array([30,35,40,38])
server_c = np.array([88,92,95,97])

combined = np.vstack([server_a, server_b, server_c]) # each array becomes a row, each row is for one server
print(combined.shape)
print(combined)

combined_cols = np.column_stack([server_a, server_b, server_c]) # each array becomes column, one metric type across all servers
print(combined_cols.shape)
print(combined_cols)

(3, 4)
[[42 55 78 91]
 [30 35 40 38]
 [88 92 95 97]]
(4, 3)
[[42 30 88]
 [55 35 92]
 [78 40 95]
 [91 38 97]]


In [1]:
#preparing data for analysis
import numpy as np
# Raw 1D CPU readings — arrives from monitoring tool
cpu = np.array([55, 60, 78, 91, 85, 30, 32, 35])

# sklearn needs (n_samples, n_features) — always 2D
X = cpu.reshape(-1, 1)
print(X.shape)    # (8, 1)

# Multiple metrics — stack then pass directly
memory = np.array([60, 65, 70, 68, 85, 40, 42, 45])
disk   = np.array([30, 32, 35, 33, 31, 20, 22, 25])

X_multi = np.column_stack([cpu, memory, disk])
print(X_multi)
print(X_multi.shape)    # (8, 3)
#Single metric needs reshape(-1, 1). Multiple metrics use column_stack — already 2D, no reshape needed.

(8, 1)
[[55 60 30]
 [60 65 32]
 [78 70 35]
 [91 68 33]
 [85 85 31]
 [30 40 20]
 [32 42 22]
 [35 45 25]]
(8, 3)


In [6]:
#Dataset
import numpy as np

cpu     = np.array([55, 60, 78, 91, 85, 30, 32, 35, 70, 75, 88, 95])
memory  = np.array([60, 65, 70, 68, 85, 40, 42, 45, 55, 58, 72, 80])
disk    = np.array([30, 32, 35, 33, 31, 20, 22, 25, 28, 30, 35, 38])

# 1. Reshape cpu into a 2D array with 4 rows and 3 columns
reshaped = cpu.reshape(4,-1)
print(reshaped)
print(reshaped.shape)

# 2. Reshape cpu into a single column for sklearn input
X = cpu.reshape(-1,1)
print(X)
print(X.shape)    # expect (12, 1)

# 3. Flatten this 2D array back to 1D
grid = np.array([[10, 20, 30], [40, 50, 60]])
flat = grid.flatten()
print(flat)

# 4. Stack cpu, memory, disk as columns
#    Result should be shape (12, 3)
X_multi = np.column_stack([cpu, memory, disk])
print(X_multi)
print(X_multi.shape)

# 5. Stack cpu, memory, disk as rows
#    Result should be shape (3, 12)
X_rows = np.vstack([cpu, memory, disk])
print(X_rows)
print(X_rows.shape)

# 6. Use -1 to reshape cpu into 2 rows
#    let NumPy figure out the columns
X_auto = cpu.reshape(2, -1)
print(X_auto)
print(X_auto.shape)   # expect (2, 6)


[[55 60 78]
 [91 85 30]
 [32 35 70]
 [75 88 95]]
(4, 3)
[[55]
 [60]
 [78]
 [91]
 [85]
 [30]
 [32]
 [35]
 [70]
 [75]
 [88]
 [95]]
(12, 1)
[10 20 30 40 50 60]
[[55 60 30]
 [60 65 32]
 [78 70 35]
 [91 68 33]
 [85 85 31]
 [30 40 20]
 [32 42 22]
 [35 45 25]
 [70 55 28]
 [75 58 30]
 [88 72 35]
 [95 80 38]]
(12, 3)
[[55 60 78 91 85 30 32 35 70 75 88 95]
 [60 65 70 68 85 40 42 45 55 58 72 80]
 [30 32 35 33 31 20 22 25 28 30 35 38]]
(3, 12)
[[55 60 78 91 85 30]
 [32 35 70 75 88 95]]
(2, 6)
